CONFIG = {
    "UWCS_DISCORD_BRIDGE_BOT_ID": 1337,
    "UWCS_MEMBER_ROLE_ID": 2674,
    "UWCS_EXEC_ROLE_IDS": [9874698723],
    "DATABASE_CONNECTION": "sqlite:///:memory:",
    "UWCS_DISCORD_ID": 1337,
    "UWCS_API_TOKEN": "api_token",
    "BOT_SECRET_KEY": "secret_key_here",
    "KARMA_TIMEOUT": 900,
    "DISCORD_TOKEN": "discord_token",
    "FIG_SAVE_PATH": "/path/to/graph/dir/",
    "FIG_HOST_URL": "https://your.url/to/host/images",
    "SQL_LOGGING": True,
    "BOT_LOGGING": True,
    "DEBUG": True,
    "REMINDER_SEARCH_INTERVAL": 30,
    "SLICER_PATH": "/path/to/prusa-slicer",
    "PRINTER_FILE_ROOT": "/path/to/print/files",
    "MUTEX_ROLES": [],  # paired as (role, conflicted role that should be removed)
}
