"""Create Event links

Revision ID: 988a71e876c3
Revises: 0963d3f2727b
Create Date: 2022-09-24 14:08:19.242479

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "988a71e876c3"
down_revision = "0963d3f2727b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_links",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("discord_event", sa.BigInteger(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("discord_event"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_links")
    # ### end Alembic commands ###
