"""added birthday db

Revision ID: b3cb0f9f62c3
Revises: e0ae8cfaebb8
Create Date: 2023-05-10 10:24:46.074625

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3cb0f9f62c3"
down_revision = "e0ae8cfaebb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "birthdays",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_birthdays_user_id_users")
        ),
        sa.PrimaryKeyConstraint("date", "age", name=op.f("pk_birthdays")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("birthdays")
    # ### end Alembic commands ###
