"""birthday table

Revision ID: d1b6228cd515
Revises: e0ae8cfaebb8
Create Date: 2023-05-09 19:22:41.687941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b6228cd515'
down_revision = 'e0ae8cfaebb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthdays',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'age', name=op.f('pk_birthdays'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthdays')
    # ### end Alembic commands ###
